version: "3.4"

networks:
  dev:
    driver: bridge

volumes:
  postgres-data:
  pgadmin-data:

services:
  web:
    container_name: web
    build:
      context: .
      dockerfile: Dockerfile
    depends_on: [ postgres ]
    ports:
      - 8080:8080
      - 4040:4040
    environment:
      ASPNETCORE_URLS: "https://+:8080;http://+:4040"
      ASPNETCORE_HTTPS_PORT: 8080
      ASPNETCORE_ENVIRONMENT: "Development"
      ConnectionStrings__DefaultConnection: "User ID=postgres;Password=1;Server=postgres;Port=5432;Database=postgres;IntegratedSecurity=true;Pooling=true;"
    volumes:
      - ${APPDATA}\microsoft\UserSecrets:/root/.microsoft/usersecrets
      - ${USERPROFILE}\.aspnet\https:/root/.aspnet/https/
    networks:
      - dev

  postgres:
    image: postgres:15-alpine
    container_name: postgres
    ports:
      - 5432:5432
    expose:
      - 5432
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: RecipeBookDb
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - dev

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    depends_on: [ postgres ]
    restart: always
    ports:
      - 5050:80
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.admin"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - dev
